name: test_10028_4_6000
suffix: ~  # add suffix to saved images
save_images: True
model: video_base
distortion: sr
save_binary: False
scale: 1
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [1]

datasets:

  test1:  # the 1st test dataset
    name: 1video
    mode: blur
    data_type: mrcs
    cord_type: star
    #dataroot: /home/evgenyn/scratch/Micrographs_part1/
    dataroot: /home/evgenyn/scratch/micro_cord/ftp.empiar.pdbj.org/archive/10028/data/Micrographs/Micrographs_part1/
    batch_size: 1
    debug: false
    debug_imgs: 5

  # test_3:  # the 1st test dataset
  #   name: on8
  #   mode: cel
  #   debug: false
  #   debug_set_size: 5
  #   alpha: 2
  #   ratio: 80

  #   dataroot_HQ: /home/evgenyn/exposute_dataset/testset_extra_exposures/exp8/
  #   dataroot_LQ: /home/evgenyn/exposute_dataset/testset_extra_exposures/exp01/


#### network structures
network_G:
  which_model_G: blur #HyperNet
  conv_size: 101
  th1: 0.1305 # double 0-1
  patch_mean: 0.82
  morphology_size: 41 
  gauss_blur_size: 25
  sqrt_frags: 8

  #blob detection
  minArea: 6000
  minThreshold: 50
  voting_th: 4


#### path
path:
  #pretrain_model_G: experiments/CEL_tune_curv/models/latest_G.pth
  pretrain_model_G: ~ #/home/evgenyn/hypernet/dce_curv/exposure_metanet/experiments/CEL_tune_extraoulation_/models/latest_G.pth
