#### general settings
name: bkur # remove the "debug" for normal training
use_tb_logger: false
model: sr
distortion: sr
scale: 1
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: cel
    debug: false
    debug_set_size: 64
    ratio: 10
    alpha: 0
    cond_norm: [1, 1]
#    cond_norm: [40, 50, 92]  # for 3D modulation
#   dataroot_GT: ../datasets/DIV2K_sub
    #images
    dataroot_HQ: "/home/evgenyn/exposute_dataset/train/exp10"
    dataroot_LQ: "/home/evgenyn/exposute_dataset/train/exp01"
    
 
    #### 3D ####
    # dataroot_LQ: ../datasets/DIV2K_3group_beta0510_k04_noise0050_q0010_41x51x47 

    use_shuffle: true
    n_workers: 16  # per GPU
    batch_size: 4
    crop_size: 512 # crop size
    save_crop: 1024
    use_flip: true
    use_trans: true
    color: RGB
  
  val:  # the 1st test dataset
    name: DIV2K
    mode: cel
    debug: true
    debug_set_size: 5
    ratio: 50
    alpha: 0.5

    use_shuffle: false
    n_workers: 8  # per GPU
    batch_size: 1
    crop_size: 1024 # crop size
    use_flip: false
    use_trans: false

    dataroot_HQ: "/home/evgenyn/exposute_dataset/train/exp5"
    dataroot_LQ: "/home/evgenyn/exposute_dataset/train/exp01"

#### network structures
network_G:
  which_model_G: CEL #HyperNet
  in_nc: 4
  out_nc: 3
  nf: 64
  nb: 32
  cond_dim: 2 # modulation dimension 2 | 3

#### path
path:
  pretrain_model_G: ~ # "experiments/CEL_lowp_archived_210919-135306/models/latest_G.pth" # None(~) for basic model; path of basic model for adafm training
  strict_load: true
  resume_state: ~ # "experiments/CEL_lowp_archived_210919-135306/training_state/400000.state"

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR

  niter: 50000
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 40000 ]  # [500000] for basic model, [1000000] for adafm-net
  lr_gamma: 0.2

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 1
  val_freq: !!float 2e4

#### logger
logger:
  wandb:
      project: microscope_enhancement
      user: neiterman21
      id: 'molecule' #if None same as name
      entity: gilb_lab
      API_KEY: e67eaf73adb041e2f73f4d41c038f40143ff8124
  print_freq: 200
  save_checkpoint_freq: !!float 2e4